sudo: required

language: node_js

node_js:
  - "node"

cache:
  directories:
    - node_modules


install:
  - nvm install node
  - npm install electron-builder@next
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
- npm run dist
